### PR TITLE
17 remove range address from config

### PR DESCRIPTION
**Pull request by VHPL-UIS**

### CODE REVIEW

**Comment by VHPL-UIS** [comment]
And the range of address doesn't change in an experiment, so, we don't need to calculate it every time.

**Comment by leandernikolaus** [comment]
Maybe you can keep the field in the config, but overwrite it when initializing the config, with a function similar to the once in `init_configs`.

**Comment by VHPL-UIS** [comment]
@leandernikolaus I think this one is ready to be merged. Please have a look.

**Review by leandernikolaus — APPROVED** [review]

**Comment by leandernikolaus** [comment]
Looks good!

**Pull request merged**
